# This is a basic workflow to help you get started with Actions

name: protobuf-productManager-go

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:

jobs:
  push-folder:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Copies and pushes generated folder
      uses: cpina/github-action-push-to-another-repository@master
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source-directory: 'gen/productManager-go/productManager'
        destination-github-username: 'nicky-marler'
        destination-repository-username: 'TapMars'
        destination-repository-name: 'protobuf-productManager-go'
        target-branch: 'main'
        user-email: 'nmarler@outlook.com'
        commit-message: 'Workflow generated'
