#This is a basic workflow that is manually triggered

name: Push-UserFirestore-Go-v1

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:

jobs:
  push-folder:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Copies and pushes generated folder
      uses: cpina/github-action-push-to-another-repository@master
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source-directory: 'gen/userFirestore-go/userFirestore/v1'
        destination-github-username: 'nicky-marler'
        destination-repository-username: 'TapMars'
        destination-repository-name: 'protobuf-userFirestore-go'
        target-branch: 'master'
        user-email: 'nmarler@outlook.com'
        commit-message: 'Workflow generated'
